### ISSUE TITLE
Fails on M2 Mac

### ISSUE THREAD

**Issue by ruze00** [abgulati/LARS#15]
After `pip install -r requirements_mac.txt`  when I do `python app.py` I get:

```
Traceback (most recent call last):
  File "/Users/ruze/workspace/reg/LARS/web_app/app.py", line 36, in <module>
    import fitz # PyMuPDF
    ^^^^^^^^^^^
  File "/Users/ruze/anaconda3/envs/lars/lib/python3.11/site-packages/fitz/__init__.py", line 22, in <module>
    from fitz.fitz import *
  File "/Users/ruze/anaconda3/envs/lars/lib/python3.11/site-packages/fitz/fitz.py", line 14, in <module>
    from . import _fitz
ImportError: dlopen(/Users/ruze/anaconda3/envs/lars/lib/python3.11/site-packages/fitz/_fitz.so, 0x0002): tried: '/Users/ruze/anaconda3/envs/lars/lib/python3.11/site-packages/fitz/_fitz.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ruze/anaconda3/envs/lars/lib/python3.11/site-packages/fitz/_fitz.so' (no such file), '/Users/ruze/anaconda3/envs/lars/lib/python3.11/site-packages/fitz/_fitz.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

There seems to be an incompatibility with `fitz` in `PyMuPDF` or with `PyMuPDF` in general.

**Comment by danialt** [comment]
have simliar issues, seems M1 is not supported by some packages needed. Would be great to test Lars on M1/2/3.

**Comment by abgulati** [comment]
Hi @ruze00 and @danialt 

Unfortunately I'm unable to test in detail on Mac since I don't own one but worry not, there's an easy solution: the docker containers in this repo have received a huge update and to make things as easy as possible, I'm also uploading pre-built images for both, the CPU-only & NvCUDA-GPU flavors so you needn't even build the container yourself!

Given this, from this point forth,, the recommended way to deploy LARS for regular use is via Docker and local setup will be recommended only for developers. Watch out for a significant update to the README documentation in the coming days.

You needn't wait until then though. Since you guys are on Mac, you'll be restrcied to the CPU-only container, please download it directly from here (Google Drive as it's way too large to host on GitHub where we're restricted to a few GB at best): https://drive.google.com/file/d/1diTTxevnyq6qMOTh-6f_YN7UBNS55Dy0/view?usp=sharing

As stated in the [Docker section](dockerized_nvidia_cuda_gpu/web_app), simply download and install [Docker Desktop](https://www.docker.com/products/docker-desktop/) to your Mac.

Once Docker is setup and the pre-built image downloaded, simply load into docker via the following terminal command:

```
docker load -i lars-cpu-only-b3408-pfr.tar
```

Ensure you create a storage volume so you can update LARS containers to newer version without losing any app data, settings & models: 

```
docker volume create lars_storage
```

Then simply run via the terminal:

```
docker run -p 5000:5000 -p 8080:8080 -v lars_storage:/app/storage lars-cpu-only-b3408-pfr
```

Then navigate to `http://localhost:5000` in  a browser and once the app loads with the [expected first run error](https://github.com/abgulati/LARS?tab=readme-ov-file#first-run---important-steps-for-first-time-setup), you can copy your LLM GGUF files into the storage volume, again via the terminal:

```
docker ps # note the container ID of the LARS container

docker cp <path_to_llm_gguf> <container_id_obtained_above>:/app/storage/models
```

While this may seem slightly involved, there a lot of  elegance & beauty to this approach:

1. It's a one-time setup
2. Beyond Docker itself, you don't need to install anything else! 
3. You get to use stuff like Azure OCR and other libs that don't work natively on Mac
4. The pre-built images are already fully-setup for use: they're "Post First-Run", thus the "pfr" suffix, indicating that all three embedding models have already been downloaded into the images so switching embedding models will be much faster and the app can be used entirely offline
5. As we're attaching a storage volume, all your app data, uploaded models and app settings will persist even when updating your container to a newer LARS container version released down the road
6. Best of all (for non-technical users), you never need to use the terminal again! On subsequent runs, just launch the Docker Desktop app and click play on the container:

![image](https://github.com/user-attachments/assets/97d10beb-1b76-4f45-914e-d9f3023daa58)

🍻

**Comment by abgulati** [comment]
Detailed resolution steps and pre-build Docker images provided, closing since no updates received.
