### ISSUE TITLE
Some requirements in requirements.txt have been yanked and requirements take a long time to get installed

### ISSUE THREAD

**Issue by astropd** [abgulati/LARS#24]
azure-ai-vision>=0.15.1b1 and opentelemetry-exporter-prometheus>=1.12.0rc1 have been yanked so they can't be downloaded with pip. Furthermore, requirements take a long time to get resolved

**Comment by abgulati** [comment]
Both those are very much present in both requirements.txt and requirements_linux.txt! You must be looking at the requirements_mac.txt file. Also dependencies are taking longer because of the change from ‘==‘ to ‘>=‘, which allows PIP’s dependency manager more flexibility. It’s a technically superior method to pass around dependencies so as to not force replace compatible versions that may already exist on your system.

**Comment by Kareem21** [comment]
![image](https://github.com/user-attachments/assets/b8d9f840-850e-49ef-b898-2545e317b981)
Getting the same issue, just a normal pip install -r requirements shows this

**Comment by Kareem21** [comment]
There's way too many issues with dependencies in requirements.. you edit one then you end up with 30 new conflicts.. Are you sure this requirements.txt is the most up to date?

**Comment by abgulati** [comment]
Hey sincere apologies, I mistook what you meant by Yanked!

Azure Vision has indeep been yanked: https://pypi.org/project/azure-ai-vision/

And replaced by: https://pypi.org/project/azure-ai-vision-imageanalysis/

Seems `opentelemetry-exporter-prometheus` is fine though:  https://pypi.org/project/opentelemetry-exporter-prometheus/

Updates to requirements & Docker build are underway: https://github.com/abgulati/LARS/issues/28#issuecomment-2379741523

Thank you for the heads-up on the yanks!

**Comment by abgulati** [comment]
@astropd @Kareem21 A new release with updated requirements is now available, please give it a spin and report your experience: https://github.com/abgulati/LARS/releases/tag/v2.0-beta7

Thank you!

**Comment by abgulati** [comment]
@astropd @Kareem21 I have now verified the requirements installation on Windows and Ubuntu: https://github.com/abgulati/LARS/blob/v2.0-beta8/requirements_linux.txt

YMMV on Fedora/DNF & Mac though!

Several unnecessary reqs have been removed and version-specs for a couple too. The encoding has also been updated to UTF-8 so you can use Nano for any required edits.

Few more refinements merged in as well, resulting in v2.0-beta8: a fast follow-up to today morning's emergency v2.0-beta7 update.

Do re-try and drop an update.

**Comment by Kareem21** [comment]
will try in a bit, i got it up and running by just using "==" on all the dependencies and removed all ">=" . That seemed to get it to work with the old requirement.txt file. Now struggling with CUDA out of memory, seems like I can ask 3-4 questions then it eats alot of memory in my C drive. I only ran app.py do I also have to run HF_waitress somewhere? didnt see it in the instructions

**Comment by abgulati** [comment]
@Kareem21 Thanks for confirming the requirements are correctly installed.

The CUDA-GPU memory fill-up was addressed in a patch yesterday: as you chat, the LLM builds it's context KV cache which most of us running local hardware simply do not have the luxury to support. Given this, CUDA-cache clearing logic was patched in.

As for your other issue, another patch has gone out today morning. Let's continue discussions for that in the dedicated issue #29  
 you've opened.

@astropd No updates from you since you first created this issue. Will leave this issue open for some time more in case you wish to add anything, else will re-close.

Thanks all 🍻
